class Error(Exception):
    pass


class SignUpError(Error):
    pass
